service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

plugins:
  - serverless-webpack  
# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"
package:
  individually: true
#resources:
#  Resources:
#      CSVProductsBucket:
#      Type: 'AWS::S3::Bucket'
#      Properties:
#        BucketName: task-5-uploaded-csv-test
#        AccessControl: PublicRead
#        CorsConfiguration:
#          CorsRules:
#            - AllowedHeaders:
#                - '*'
#              AllowedMethods:
#                - GET
#                - PUT
#                - HEAD
#              AllowedOrigins:
#                - '*'
#  Outputs:
#    BucketName:
#      Value: !Ref CSVProductsBucket
#      Description: Name of the bucket for CSV with CORS enabled.

functions:
  importProductsFile:
    handler: functions/importProductsFile/importProductsFile.handler
    events:
      - http:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true